name = "browser-worker"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

browser = { binding = "MYBROWSER" }

[observability]
enabled = true

[vars]
EMAIL = "vinimdocarmo@gmail.com"